### PR TITLE
LGA-3224 Add in Authorisation to the API

### PR DESCRIPTION
**Pull request by said-moj**
## What does this pull request do?

Add in Authorisation to the API.
Add management commands to list and update users scopes

## Any other changes that would benefit highlighting?

Added the four scopes CREATE,READ,UPDATE and DELETE.

Routes that needed a specific scope can include the following parameter in their http method annotation:
```dependencies=[Security(get_current_active_user, scopes=[UserScopes.X])],```

### Adding scopes to users
Run the following management command to add scopes to a user
```python manage.py user-scopes-add <username> --scope=<scope> --scope<another scope>```

To get a list of user scopes
```python manage.py user-scopes-list <username>```

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

### CODE REVIEW

**Review by BenMillar-MOJ — CHANGES_REQUESTED** [review]
Would you be able to add documentation markdown file to `docs/souce/documentation` around, what scopes we have and how they can be used, along with how to use the management commands please.

Many thanks! 😄

**Review by TawneeOwl — APPROVED** [review]
Looks good!!!

**Comment by said-moj** [comment]
> Would you be able to add documentation markdown file to `docs/souce/documentation` around, what scopes we have and how they can be used, along with how to use the management commands please.
> 
> Many thanks! 😄

I have updated the `docs/source/documentation/case.html.md.erb` to include the scopes required for each api call
I have also created `docs/source/documentation/scopes.erb` which contains the developer documentation about scopes and how to add and list them

**Review by BenMillar-MOJ — APPROVED** [review]
LGTM, thank you so much for this. This is really great! 👍

**Pull request merged**
